swagger: '2.0'
info:
  description: |
    Official documentation for Hulk's RESTful API.
  version: '1.0'
  title: Hulk - RESTful API Specification
  contact:
    name: Hulk on GitHub
    url: https://github.com/squaresLab/Hulk
host: localhost
basePath: /v1

###############################################################################

definitions:
  TransformationSchema:
    type: object
    required:
      - match
      - rewrite
    properties:
      match:
        type: string
        description: The Rooibos matching pattern that should be used to
          identify mutation targets in the source code.
        example: "if (:[1])"
      rewrite:
        type: string
        description: The Rooibos rewrite pattern that should be used to
          mutate identified mutation targets.
        example: "if (!(:[1]))"

  Language:
    type: object
    required:
      - name
      - file-endings
    properties:
      name:
        type: string
        description: The name of the language.
        example: Python
      file-endings:
        type: array
        items:
          type: string
          description: An acceptable file ending for this language.
          example: '.py'

  Operator:
    type: object
    required:
      - name
      - languages
      - transformations
    properties:
      name:
        type: string
        description: A unique identifier for this operator.
        example: NEGATE_IF_CONDITION_CSTYLE
      languages:
        type: array
        items:
          $ref: '#/definitions/Language'
      transformations:
        type: array
        items:
          $ref: '#/definitions/TransformationSchema'

################################################################################

paths:
  /operators:
    get:
      summary: List of registered mutation operators.
      description: >-
        Produces a list of all the mutation operators that are registered with
        this server given by their unique identifiers.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: string
              description: The unique identifier of the mutation operator.
              example: NEGATE_IF_CONDITION_CSTYLE

  /operators/${id}:
    get:
      summary: Description of a mutation operator.
      description: >-
        Produces a description of a mutation operator that is associated with
        a given unique identifier.
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          description: The unique identifier of the mutation operator.
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Operator'
        404:
          description: Operator not found.
